[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Pathfinder Project Україна"
authors = [{name = "Deniz Köse"}]
dynamic = ["version", "description"]
